### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by toxic-johann** [toxic-johann/is-pwa-ready#2]
- [x] add title of browser
- [x] mention what each color are yellow, green, grey etc
- [x] language change switch
- [x] fix auto test bug on UC and QQ browser
- [x] finish fully cache test case
- [x] add push subscribe test case

**Comment by awebdeveloper** [comment]
@toxic-johann Looks great now  Include yandex

**Comment by awebdeveloper** [comment]
Also send a pr to caniuse to include yours in notes

**Comment by toxic-johann** [comment]
@awebdeveloper It seems i can not find yandex in China. Can you do that test by auto test page for me?

**Comment by awebdeveloper** [comment]
sorry. i didn't get what you need. Plus i don't have yandex
